name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # Step 3: Download modules
      - name: Install dependencies
        run: go mod download

      # Step 4: Run linters (golangci-lint)
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

      - name: Run golangci-lint
        run: ./bin/golangci-lint run

      # Step 5: Run tests
      - name: Run tests
        run: go test -v ./...

      # (Optional) Step 6: Generate and show coverage
      # Uncomment this section if you want coverage output in the logs
      - name: Test coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
